### PR TITLE
Using simple-statistics functions instead of handwritten

### LINKED ISSUE #60: Replace hand-written summarizers with calls to simple-statistics library functions
See https://simplestatistics.org/docs/

### PR DESCRIPTION
**Pull request by gvwilson**
Closes #60.

### CODE REVIEW

**Comment by MayaGans** [comment]
Just pulled down this PR and started playing with the summarize block....

Screen Shot 2020-07-29 at 11 07 14 AM

Am I wrong to be expecting something like this:

```
> library(palmerpenguins)
> library(dplyr)
> library(magrittr)
> 
> penguins %>%
+   group_by(species) %>%
+   summarise(mean = mean(bill_length_mm))
`summarise()` ungrouping output (override with `.groups` argument)
# A tibble: 3 x 2
  species    mean
  <fct>     <dbl>
1 Adelie     NA  
2 Chinstrap  48.8
3 Gentoo     NA  
```

Or this depending how we deal with NAs

```
> penguins %>%
+   group_by(species) %>%
+   summarise(mean = mean(bill_length_mm, na.rm = TRUE))
`summarise()` ungrouping output (override with `.groups` argument)
# A tibble: 3 x 2
  species    mean
  <fct>     <dbl>
1 Adelie     38.8
2 Chinstrap  48.8
3 Gentoo     47.5
> 
```

**Comment by gvwilson** [comment]
You should wind up with a new column called `mean_bill_length_mm` with the mean values for each species. There will be the same number of rows as the input table - to get down to three rows, select `Species` and `mean_bill_length_mm` and then add a `unique` block.

**Comment by MayaGans** [comment]
I don't see that new column being generated....

**Comment by MayaGans** [comment]
Console output:

```
* read penguins
* summarize mean bill_length_mm
```

So I'm not (entirely) crazy

**Comment by MayaGans** [comment]
Not sure if you saw @gvwilson's comment on slack @DarkMetroid but there should be a new "result" table in the dropdown right? I feel like that's different bug from this PR but it's hard to check this one without seeing the "result" table.... thoughts?

Screen Shot 2020-07-29 at 1 25 13 PM

**Comment by DarkMetroid** [comment]
@MayaGans that makes sense, currently the table just looks at env.ui.userData (i.e. nothing really grabs env.results).

I can show both pretty easily in the same dropdown, but the one concern would be duplicate names (e.g. if someone named their Report 'penguins' or 'earthquakes'). Thoughts on how we should handle that? @gvwilson

**Comment by gvwilson** [comment]
Can you style the pulldown so that data tables are plain font and results are italic or vice versa?

**Comment by DarkMetroid** [comment]
Yeah, that's doable. I might be able to get a different icon to display before each to make it more clear too.

**Pull request merged**
